services:

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=testDB
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DATABASE_URL=postgres://postgres:root@db:5432/testDB
    depends_on:
      - db
    command: >
      sh -c "composer install --prefer-dist --no-progress --optimize-autoloader && php artisan serve --host=0.0.0.0 --port=8000"
  

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testDB
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - app-network
    ports:
      - "8888:80"
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data: