server {
       listen 80;
       server_name localhost;

       location / {
           root /usr/share/nginx/html;  # Путь к вашим собранным файлами Vue
           try_files $uri $uri/ /index.html;  # Если файл не найден, перенаправляем на index.html
       }
}